# Spring Application
spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:h2:mem:connecthubdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Server Port
server.port=8080

# App Specific - JWT
app.jwt.secret=MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
app.jwt.expiration-ms=86400000

# App Specific - CORS
app.cors.allowed-origin=http://localhost:5173

# File Upload
app.upload-dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Data Initialization
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=create-drop